### ISSUE TITLE
Too many values to unpack

### ISSUE THREAD

**Issue by bkonia** [edavis/pandoc-opml#2]
Hi Eric,

I'm getting the following errors when I run a conversion on any Markdown document:

```
C:\Users\brad\Downloads>pandoc-opml warmup.md
Traceback (most recent call last):
  File "C:\Users\brad\AppData\Local\Programs\Python\Python39\Scripts\pandoc-opml-script.py", line 33, in <module>
    sys.exit(load_entry_point('pandoc-opml==0.1', 'console_scripts', 'pandoc-opml')())
  File "c:\users\brad\appdata\local\programs\python\python39\lib\site-packages\pandoc_opml\__init__.py", line 227, in main
    p = PandocOPML(json_ast)
  File "c:\users\brad\appdata\local\programs\python\python39\lib\site-packages\pandoc_opml\__init__.py", line 30, in __init__
    self.head, self.body = json.loads(json_ast)
ValueError: too many values to unpack (expected 2)
```

**Comment by huyz** [comment]
Some simple fixes are needed: PR https://github.com/edavis/pandoc-opml/pull/4
